### ISSUE TITLE
Complete update of the ontodoc tool

### ISSUE THREAD

**Issue by jesper-friis** [emmo-repo/EMMOntoPy#759]
# Description
Rewrite and simplify the ontodoc tool such that it is easy to use for both EMMO and EMMO-based domain ontologies. 

The new version is based on the solution in domain-battery. For now the python module is called ontodoc_rst.py.

Structure the generated document as follows:

```
==========
References
==========

Module: <first_module_name>
===========================

-------
Classes
-------

<class1>
--------

...
```

For each module, document:
- classes
- object properties
- data properties
- annotation properties
- individuals
- datatypes

## Tasks
- [x] Reproduce all information included in the [battery.rst] (https://github.com/emmo-repo/domain-battery/blob/master/sphinx/battery.rst) file. [PR #742]
- [x] Add tooling for creating other needed files, like `index.rst` (just a template that the user can improve). [PR #742]
- [x] Add a new ontodoc script/tool - instead of adding a new tool, the old ontodoc tool was extended to support `.rst` output. It doesn't run sphinx automatically, though... [PR #742]
- [ ] Add option to ontodoc to run sphinx automatically
- [ ] Add small tutorial of how to use the tool
- [ ] Add ontology metadata documentation to generated documentation
- [ ] Add more semantic information to generated documentation
- [ ] Add language to keys for localised values
- [ ] Add default css file (common for all EMMO domain ontologies, could e.g. be downloaded from a common source...)
- [ ] Add support for figures (e.g. by displaying links to known image formats as images)
- [ ] Sort modules in a logical order, e.g. by namespace and import depth
- [ ] Add a module dependency graph at the top
- [ ] Add subclasses to generated documentation to support navigating the taxonomy
- [ ] Is it possible to collapse the sidebar to make it easier to navigate to the right module?
- [ ] Add anchor by prefLabel, to make it easier for people to find the IRI when one knows the prefLabel
